config/routes.rb
Rails.application.routes.draw do
  root 'leaderboard#index'

  get 'game/new'
  post 'game/create'
  get 'people', to: 'person#list'
  scope 'stats' do
    get 'fact', to: 'stats#fact'
  end

  get '/u/:id', to: 'person#show', as: 'person'

  get '/notloggedin', to: 'sessions#new', as: 'login'
  get '/notallowed', to: 'sessions#denied', as: 'not_allowed'
  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/controllers/leaderboard_controller.rb
class LeaderboardController < ApplicationController
  before_action :get_season

  def index
    @leaderboards = []
    GameType.all().each do |game_type|
      if @season.present?
        people = Person.includes(person_games: [game: [:game_type]]).where('game_types.name': game_type.name, 'games.created_at': @season[:start]..@season[:finish])
        max_person_game_query = PersonGame.select('count(person_id) as num').joins('inner join games on games.id=person_games.game_id').joins('inner join game_types on game_types.id=games.game_type_id').where('game_types.name': game_type.name, 'games.created_at': @season[:start]..@season[:finish]).group('person_id').order('num desc').limit(1).first()
        max_games_played = if max_person_game_query then max_person_game_query.num else 0 end
      else
        people = Person.includes(person_games: [game: [:game_type]]).where('game_types.name': game_type.name)
        max_person_game_query = PersonGame.select('count(person_id) as num').joins('inner join games on games.id=person_games.game_id').joins('inner join game_types on game_types.id=games.game_type_id').where('game_types.name': game_type.name).group('person_id').order('num desc').limit(1).first()
        max_games_played = if max_person_game_query then max_person_game_query.num else 0 end
      end

      if game_type.reverse_points
        sorted_people = people.sort_by{ |person| [person.win_percentage(game_type.id, max_games_played, @season), person.points_per_game(game_type.id, @season) * (-1)] }
      else
        sorted_people = people.sort_by{ |person| [person.win_percentage(game_type.id, max_games_played, @season), person.points_per_game(game_type.id, @season)] }
      end
      @leaderboards.push({
          :game => game_type.name,
          :game_type_id => game_type.id,
          :people => sorted_people.reverse,
          :max_games_played => max_games_played
      })
    end

    if @season.present?
      @games = Game.where(created_at: @season[:start]..@season[:finish]).order(created_at: :desc).limit(50)
    else
      @games = Game.all().order(created_at: :desc).limit(50)
    end
  end

end

app/views/leaderboard/_board.html.erb
<div class="leaderboard__title"><%= board[:game] %></div>
<table class="leaderboard__table" id="leaderboard__table_<%= index %>">
  <thead>
    <tr>
      <th class="medal-header"></th>
      <th class="sort" data-sort="name">Name</th>
      <th class="leaderboard__table__game sort" data-sort="games">Games</th>
      <th class="sort" data-sort="wins">Wins</th>
      <th class="sort" data-sort="win-perc">Win%</th>
      <th class="sort" data-sort="ppg">PPG</th>
    </tr>
  </thead>
  <tbody class="list">
    <% board[:people].each_with_index do |person, index| %>
    <% medalClasses = ['gold', 'silver', 'bronze'] %>
      <% if index < 3 %>
        <tr class="<%= medalClasses[index] %>-row">
      <% else %>
        <tr>
      <% end %>
        <td class="medal-cell">
          <% if index < 3 %>
            <span class="fa-stack <%= medalClasses[index] %>-medal">
              <i class="fa fa-circle fa-stack-2x"></i>
              <i class="fa fa-star fa-stack-1x fa-inverse"></i>
            </span>
          <% end %>
        </td>
        <td class="name"><%= link_to person.name, person_path(person) %></td>
        <td class="leaderboard__table__game games"><%= person.games_played_by_game_type(board[:game_type_id], @season) %></td>
        <td class="wins"><%= person.wins(board[:game_type_id], @season) %></td>
        <td class="win-perc"><%= person.win_percentage(board[:game_type_id], board[:max_games_played], @season).round(2) %></td>
        <td class="ppg"><%= person.points_per_game(board[:game_type_id], @season).round(2) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div id="leaderboard__table_<%= index %>__hidden" class="hidden__container" hidden>
  <span class="hidden__message"></span>
  <a href="#" class="hidden__show-all">Show all</a>
</div>

app/views/leaderboard/_game_panel.html.erb
<div class="game__panel">
  <div class="mui-panel">

    <div class="game__header">
      <div class="mui--text-caption mui--text-dark-hint">
        <span class="moment-format"><%= game.created_at.to_formatted_s(:iso8601) %></span> a game of <%= game.game_type.name %> was played
      </div>
      <div class="game__header__title">
        Winner
      </div>
      <div class="game__header__winner">
        <i class="fa fa-trophy fa-4x"></i><span class="mui--text-display2"><%= game.winner %></span>
      </div>
    </div>

    <div class="game__content">
      <% game.leaderboard.each do |person| %>
        <div class="game__score">
          <%= person.person.name %>
          <span class="game__score__tally"><%= person.points.to_s %></span>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/leaderboard/index.html.erb
<% content_for :season do %>
  <% if @season.present? %>
    <a href="<%= url_for root_url :params => {season: @season[:start].advance(days: -1).strftime("%Y-%m-%d")} %>" class="mui-btn mui-btn--accent season-btn">
      <%= fa_icon "chevron-left" %>
    </a>
    <i class="fa fa-calendar"></i>
    <%= @season[:start].strftime("%b.") + ' to ' + @season[:finish].strftime("%b. %Y") %>
    <a href="<%= url_for root_url :params => {season: @season[:finish].advance(days: 1).strftime("%Y-%m-%d")} %>" class="mui-btn mui-btn--accent season-btn">
      <%= fa_icon "chevron-right" %>
    </a>
    <a href="/?season=all" class="mui-btn mui-btn--accent season-btn js-test-all-time">
      All time
    </a>
  <% else %>
    <i class="fa fa-calendar"></i> All time
    <a href="<%= url_for root_url %>" class="mui-btn mui-btn--accent season-btn">
      Go to current
    </a>
  <% end %>
<% end %>

<% if @games.empty? %>
  <div class="empty__container">
    <i class="fa fa-frown-o fa-5x" aria-hidden="true"></i>
    <p>Welp, you need to play some games.</p>
  </div>
<% else %>
  <div class="leaderboard__container">
    <% @leaderboards.each_with_index do |board, index| %>
      <% if !board[:people].empty? %>
        <%= render partial: "board", locals: {board: board, index: index} %>
      <% end %>
    <% end %>
  </div>

  <div class="game__container">
    <div class="stats__container mui--hidden-sm mui--hidden-xs">
      <div id="random-fact"></div>
    </div>
    <% @games.each do |game| %>
      <%= render partial: "game_panel", locals: {game: game} %>
    <% end %>
  </div>
<% end %>