config/routes.rb
Rails.application.routes.draw do
  root 'leaderboard#index'

  get 'game/new'
  post 'game/create'
  get 'people', to: 'person#list'
  scope 'stats' do
    get 'fact', to: 'stats#fact'
  end

  get '/u/:id', to: 'person#show', as: 'person'

  get '/notloggedin', to: 'sessions#new', as: 'login'
  get '/notallowed', to: 'sessions#denied', as: 'not_allowed'
  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/views/layouts/_game_types_js.html.erb
<script>
var gameTypes = {
  <% @game_types.each do |type| %>
    "<%= type.id %>": <%= type.reverse_points %>,
  <% end %>
};
</script>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <title>Pointy</title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Cabin|Abel" rel="stylesheet">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="mui-appbar mui--z1">
      <div class="mui-container-fluid">
        <table width="100%">
          <tr class="mui--appbar-height">
            <td class="mui--text-title header--link"><%= link_to 'Pointy', root_url %></td>
            <td class="mui--appbar-height mui--appbar-min-height mui--hidden-sm mui--hidden-xs season__container">
              <%= yield :season %>
            </td>
            <td>
              <a href="<%= url_for game_new_url %>" class="mui-btn mui-btn--accent mui--pull-right js-test-add-points">
                <%= fa_icon "plus", text: "Add points" %>
              </a>
            </td>
            <!-- <td>
              <a href="/auth/google" class="mui-btn mui-btn--accent mui--pull-right">
                <%= fa_icon "plus", text: "Login" %>
              </a>
            </td> -->
          </tr>
        </table>
      </div>
    </header>


    <div class="mui--appbar-height"></div>
    <div class="season__container season__container--mobile mui--visible-sm-block mui--visible-xs-block">
      <%= yield :season %>
    </div>
    <%= yield %>

  </body>
</html>